from scapy.arch import get_if_addr

SERVER_PORT = 2002
DESTINATION_PORT = 13117
OFFER_TIME_OUT = 10

TEAM_NAME_SIZE = 32
TYPE_SIZE = 1
HASH_SIZE = 40
ORIGINAL_LENGTH = 1
ORIGINAL_STRING_LENGTH = 256
ORIGINAL_STRING_END = 256

MAX_UDP_MSG_SIZE = TEAM_NAME_SIZE + TYPE_SIZE + HASH_SIZE + ORIGINAL_LENGTH + ORIGINAL_STRING_LENGTH + ORIGINAL_STRING_END

MAX_TCP_SIZE_BUFFER = 40960

MAGIC_COOKIE = 0xfeedbeef
UDP_MSG_TYPE = 0x2

MESSAGE_FORMAT = 'Ibh'

TEAM_NAME = "team_name\n"
EMPTY_IP = ""
LOCAL_IP = "127.0.0.1"
DEV_IP = "172.1.0.2"
TEST_IP = get_if_addr('eth2')

IP = DEV_IP
